colorscheme solarized
set t_Co=16
syntax on
set number
set textwidth=80
set cursorline
set showcmd
set title
set laststatus=2
set autoread
set splitright
set splitbelow
set nobackup
set nowb
set noswapfile
set incsearch
set hlsearch
set smartindent
set autoindent
set wildmenu
set wildmode=longest,list,full
set list
set listchars=eol:$,tab:>-,trail:^
